# Generated by Django 6.1.1 on 2026-09-30 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='teléfono')),
                ('address', models.CharField(blank=True, help_text='Calle y número de la vivienda (ej.: Los Aromos 1234).', max_length=200, verbose_name='dirección')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva')], default='active', max_length=20, verbose_name='estado')),
                ('managers', models.CharField(blank=True, max_length=255, null=True, verbose_name='responsables')),
                ('scope', models.CharField(blank=True, max_length=100, null=True, verbose_name='ámbito')),
            ],
            options={
                'verbose_name': 'Delegación',
                'verbose_name_plural': 'Delegaciones',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('valid_from', models.DateField(verbose_name='vigencia desde')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='vigencia hasta')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('calculation_type', models.CharField(choices=[('quantitative', 'Cuantitativo'), ('qualitative', 'Cualitativo')], default='quantitative', max_length=20, verbose_name='tipo de cálculo')),
                ('parent_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_items', to='organization.item', verbose_name='ítem padre (tipo de atención)')),
            ],
            options={
                'verbose_name': 'Ítem',
                'verbose_name_plural': 'Ítems',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('institutional_id', models.CharField(max_length=20, unique=True, verbose_name='identificador institucional')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20, verbose_name='estado')),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='officers', to='organization.delegation', verbose_name='delegación')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='officers', to='organization.position', verbose_name='cargo')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ('delegation__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PositionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ponderador')),
                ('valid_from', models.DateField(verbose_name='vigencia desde')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='vigencia hasta')),
                ('kind', models.CharField(choices=[('NORMAL', 'Normal'), ('BONUS', 'Bonificación'), ('PENALTY', 'Penalización')], default='NORMAL', max_length=20, verbose_name='tipo')),
                ('max_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='tope máximo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_items', to='organization.item', verbose_name='ítem')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_items', to='organization.position', verbose_name='cargo')),
            ],
            options={
                'verbose_name': 'Ítem de cargo',
                'verbose_name_plural': 'Ítems de cargo',
                'ordering': ('position__name', 'item__name'),
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='territories', to='organization.delegation', verbose_name='delegación')),
            ],
            options={
                'verbose_name': 'Territorio',
                'verbose_name_plural': 'Territorios',
                'ordering': ('delegation__name', 'name'),
                'constraints': [models.UniqueConstraint(fields=('name', 'delegation'), name='uq_territory_delegation')],
            },
        ),
    ]
