# Generated by Django 6.1.1 on 2026-09-30 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('event', models.CharField(max_length=100, verbose_name='evento')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('affected_entity', models.CharField(max_length=50, verbose_name='entidad afectada')),
                ('record_id', models.PositiveIntegerField(verbose_name='identificador del registro')),
                ('previous_value', models.TextField(blank=True, null=True, verbose_name='valor anterior')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='valor nuevo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ('-date',),
            },
        ),
    ]
