# Generated by Django 6.1.1 on 2026-09-30 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20, verbose_name='estado')),
                ('officer', models.OneToOneField(blank=True, help_text='Vacío solo para cuentas técnicas (superusuario) sin un funcionario asociado en terreno.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profile', to='organization.officer', verbose_name='funcionario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
    ]
