# Generated by Django 6.1.1 on 2026-09-30 20:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(verbose_name='fecha de término')),
                ('computable_days', models.PositiveIntegerField(verbose_name='días computables')),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('active', 'Vigente'), ('closed', 'Cerrado')], default='planned', max_length=20, verbose_name='estado')),
                ('collective_threshold', models.DecimalField(decimal_places=2, default=80, max_digits=5, verbose_name='umbral colectivo')),
                ('amber_threshold', models.DecimalField(decimal_places=2, default=60, max_digits=5, verbose_name='umbral ámbar')),
                ('weighted_cap', models.DecimalField(decimal_places=2, default=150, max_digits=5, verbose_name='tope ponderado')),
                ('parameters_version', models.CharField(default='1', max_length=20, verbose_name='versión de parámetros')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Debe ser mayor a 0 (equivale al CHECK del script SQL).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='valor objetivo')),
                ('unit', models.CharField(max_length=50, verbose_name='unidad')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ponderador')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versión')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='organization.item', verbose_name='ítem')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='organization.officer', verbose_name='funcionario')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='organization.position', verbose_name='cargo')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='planning.period', verbose_name='período')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ('-period__start_date',),
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('progress', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='avance')),
                ('compliance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='cumplimiento')),
                ('weighting', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ponderación')),
                ('status_light', models.CharField(choices=[('green', 'Verde'), ('amber', 'Ámbar'), ('red', 'Rojo')], max_length=20, verbose_name='semáforo')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de cálculo')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='planning.goal', verbose_name='meta')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ('-calculated_at',),
            },
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('kind', models.CharField(choices=[('bonus', 'Bonificación'), ('penalty', 'Penalización')], max_length=20, verbose_name='tipo')),
                ('reason', models.CharField(max_length=255, verbose_name='motivo')),
                ('percentage_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='valor (%)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='organization.officer', verbose_name='funcionario')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='usuario responsable')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='planning.period', verbose_name='período')),
            ],
            options={
                'verbose_name': 'Ajuste',
                'verbose_name_plural': 'Ajustes',
                'ordering': ('-date',),
            },
        ),
    ]
