# Generated by Django 6.1.1 on 2026-09-30 20:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Tipo de gestión',
                'verbose_name_plural': 'Tipos de gestión',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('date', models.DateField(verbose_name='fecha')),
                ('request_description', models.TextField(blank=True, verbose_name='solicitud / problema')),
                ('action_taken', models.TextField(blank=True, verbose_name='acción')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='contacto')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('status', models.CharField(choices=[('registered', 'Registrada'), ('in_progress', 'En proceso'), ('closed', 'Cerrada')], default='registered', max_length=30, verbose_name='estado')),
                ('requires_visit', models.BooleanField(default=False, verbose_name='requiere visita')),
                ('added_to_pipeline', models.BooleanField(default=False, help_text='Si queda marcado, la actividad se refleja como Commitment en la agenda colectiva (tubo de trabajo).', verbose_name='ingresa al tubo de trabajo')),
                ('author_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_activities', to='organization.officer', verbose_name='funcionario autor')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='organization.beneficiary', verbose_name='beneficiario')),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='organization.delegation', verbose_name='delegación')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='organization.item', verbose_name='ítem')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='organization.service', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='origen')),
                ('request_date', models.DateField(blank=True, null=True, verbose_name='fecha de solicitud')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('requester', models.CharField(max_length=100, verbose_name='solicitante')),
                ('requester_type', models.CharField(choices=[('INTERNAL', 'Interno'), ('EXTERNAL', 'Externo')], default='EXTERNAL', max_length=10, verbose_name='tipo de solicitante')),
                ('due_date', models.DateField(verbose_name='fecha comprometida')),
                ('support', models.CharField(blank=True, max_length=100, null=True, verbose_name='apoyo')),
                ('status', models.CharField(choices=[('submitted', 'Ingresado'), ('in_progress', 'En proceso'), ('fulfilled', 'Cumplido')], default='submitted', max_length=30, verbose_name='estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='observación')),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='organization.delegation', verbose_name='delegación')),
                ('responsible_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_commitments', to='organization.officer', verbose_name='funcionario responsable')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='organization.territory', verbose_name='territorio')),
            ],
            options={
                'verbose_name': 'Compromiso',
                'verbose_name_plural': 'Compromisos',
                'ordering': ('-due_date',),
            },
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('sequence_number', models.PositiveSmallIntegerField(help_text='1ra, 2da o 3ra gestión sobre la misma actividad.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='número de gestión')),
                ('date', models.DateField(verbose_name='fecha')),
                ('result', models.CharField(max_length=255, verbose_name='resultado')),
                ('scheduled_visit_date', models.DateField(blank=True, null=True, verbose_name='fecha programada de visita')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='fecha de visita')),
                ('report_delivery_date', models.DateField(blank=True, null=True, verbose_name='fecha de entrega de informe')),
                ('benefit_delivery_date', models.DateField(blank=True, null=True, verbose_name='fecha de entrega de beneficio')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followups', to='operations.activity', verbose_name='actividad')),
                ('management_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='followups', to='operations.managementtype', verbose_name='tipo de gestión')),
            ],
            options={
                'verbose_name': 'Gestión de atención',
                'verbose_name_plural': 'Gestiones de atención',
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('activity', 'sequence_number'), name='uq_activity_followup')],
            },
        ),
    ]
