# Generated by Django 6.1.1 on 2026-09-30 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('unique_code', models.CharField(max_length=50, unique=True, verbose_name='código único')),
                ('file_link', models.CharField(help_text='Nombre/ruta del archivo en el repositorio de evidencia (ej. Google Drive), tal como se usa en la Matriz real.', max_length=255, verbose_name='archivo / vínculo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de carga')),
                ('review_status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=30, verbose_name='estado de revisión')),
                ('metadata', models.TextField(blank=True, null=True, verbose_name='metadatos')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_records', to='operations.activity', verbose_name='actividad')),
                ('author_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_evidence', to='organization.officer', verbose_name='funcionario autor')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Borrado lógico: si tiene fecha, el registro está archivado.', null=True, verbose_name='eliminado el')),
                ('decision', models.CharField(choices=[('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('flagged', 'Observado')], max_length=30, verbose_name='decisión')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='observación')),
                ('result', models.CharField(blank=True, max_length=50, null=True, verbose_name='resultado')),
                ('version', models.CharField(default='1', max_length=20, verbose_name='versión')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations', to='evidence.evidence', verbose_name='evidencia')),
                ('reviewer_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_validations', to='organization.officer', verbose_name='funcionario verificador')),
            ],
            options={
                'verbose_name': 'Validación',
                'verbose_name_plural': 'Validaciones',
                'ordering': ('-date',),
            },
        ),
    ]
